package dani.java.examenuf6.model;
// Generated Apr 16, 2015 1:05:43 PM by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Double price;
     private Boolean ticketsAvailable;
     private Date data;
     private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public Event() {
    }

    public Event(String name, String description, Double price, Boolean ticketsAvailable, Date data) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.ticketsAvailable = ticketsAvailable;
        this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Boolean getTicketsAvailable() {
        return this.ticketsAvailable;
    }
    
    public void setTicketsAvailable(Boolean ticketsAvailable) {
        this.ticketsAvailable = ticketsAvailable;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    @Override
    public String toString() {
        return "Event{" + "id=" + id + ", name=" + name + ", description=" + description + ", price=" + price + ", ticketsAvailable=" + ticketsAvailable + ", data=" + data + '}';
    }

}


